{
 "title": "APF",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "apiserver_flowcontrol_request_concurrency_in_use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_request_concurrency_in_use",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver_flowcontrol_current_inqueue_requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_current_inqueue_requests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver_flowcontrol_request_concurrency_limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_request_concurrency_limit",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver_flowcontrol_dispatched_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_dispatched_requests_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver_flowcontrol_request_execution_seconds_count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_request_execution_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver_flowcontrol_request_execution_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_request_execution_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver_flowcontrol_request_wait_duration_seconds_count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_request_wait_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver_flowcontrol_request_wait_duration_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "apiserver_flowcontrol_request_wait_duration_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}